# Name of the composite action
name: install

inputs:
  image: 
    description: 'Input image for FlashTest'
    required: true

runs:
  using: "composite"
  steps:
    - run: maple container pour --image=${{inputs.image}} 
      shell: bash
    - run: maple container execute 'pip3 install click && ./setup develop && ./setup install && ./setup clean'
      shell: bash
    - run: maple container commit --image=${{inputs.image}}
      shell: bash
    - run: maple container rinse
      shell: bash
